package com.fitplanner.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Document("forum_topics")
@NoArgsConstructor
@AllArgsConstructor
public class ForumTopic {
    @Id
    private String id; // id is a String containing the MongoDB ObjectId, this is automatically
                       // generated - Batuhan
    @Indexed(unique = true) // for not allowing duplicate titles - Batuhan
    private String title; // title is a String containing the topic's title - Batuhan

    // All basic getters and setters are generated by lombok, we don't need to worry
    // - Batuhan
    public ForumTopic(String title) {
        super();
        this.title = title;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getId() {
        return id;
    }

}
