package com.fitplanner.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Document("forum_comments")
@NoArgsConstructor
@AllArgsConstructor
public class ForumComment {
    @Id
    private String id;

    @DBRef
    private User user;

    @DBRef
    private ForumTopic topic;

    private String text;

    public ForumComment(User user, ForumTopic topic, String text) {
        super();
        this.user = user;
        this.topic = topic;
        this.text = text;
    }

    // All basic getters and setters are generated by lombok, we don't need to worry
    // - Batuhan

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public ForumTopic getTopic() {
        return topic;
    }

    public void setTopic(ForumTopic topic) {
        this.topic = topic;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getId() {
        return id;
    }

}
